### ISSUE TITLE
Beatmap distances are not recalculated on different maps with the same diff name

### ISSUE THREAD

**Issue by hikizisa** [Darius-Wattimena/MapsetChecksCatch#1]
https://github.com/Darius-Wattimena/MapsetChecksCatch/blob/aa3f6bbba7a19b867f670e3530bfbabbbfd89789/Checks/General/CheckBeatmapSetDistanceCalculation.cs#L46-L48

static variable SetBeatmaps keeps object datas even when user checks different mapsets.
Thus when a diff with the same diff name is calculated, TryAdd fails and that new diff uses datas from the other diff.

```
var calculatedBeatmap = BeatmapDistanceCalculator.Calculate(beatmap);
SetBeatmaps.TryRemove(beatmap.metadataSettings.version, out var catchObjects);
SetBeatmaps.TryAdd(beatmap.metadataSettings.version, calculatedBeatmap);
```

You can add TryRemove there to update object datas when user checks new mapset

**Comment by Darius-Wattimena** [comment]
Good point, I actually didn't think about this. Feel free to create a PR with the fix if you want.

**Comment by hikizisa** [comment]
sure, created a PR with the fix
