### ISSUE TITLE
IssueTemplate name is wrong for sliderhyperdashes check

### ISSUE THREAD

**Issue by hikizisa** [Darius-Wattimena/MapsetChecksCatch#3]
https://github.com/Darius-Wattimena/MapsetChecksCatch/blob/ddf212f88168c077bc8e04cf938089e1ada3b3ea/Checks/Compose/Rain/CheckBasicSnappedHyperdash.cs#L40-L62
https://github.com/Darius-Wattimena/MapsetChecksCatch/blob/ddf212f88168c077bc8e04cf938089e1ada3b3ea/Checks/Compose/Rain/CheckBasicSnappedHyperdash.cs#L99-L107

In Rain/CheckBasicSnappedHyperdash.cs, apparently line 102 should get template for "SliderHyperdashes" but "ConsecutiveHyperdashes" is written instead, implementation of the file seems incomplete as an actual consecutive hyperdash check doesn't seem to present

there was an issue while opening mapset like https://osu.ppy.sh/beatmapsets/903381#fruits/1885868 perhaps due to this ("The given key 'ConsecutiveHyperdashes' was not present in the dictionary.")

**Comment by Darius-Wattimena** [comment]
Will be fixed in the next release, thanks for pointing it out!
